name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

 [[d1_databases]]
 binding = "DB"
 database_name = "blazenote"
 database_id = "b63f39f5-baa2-4213-9b62-8d8a00be8924"
 migrations_dir = "./migrations"

# [ai]
# binding = "AI"

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"

[observability.logs]
enabled = true
